// Shared PlayWords Kids course core.
// Keep platform-neutral data and lesson generation here so Web and WeChat Mini Program can reuse one source.
(function initPlayWordsCore(root, factory) {
  const core = factory();
  if (typeof module !== "undefined" && module.exports) {
    module.exports = core;
  }
  root.PlayWordsCore = core;
})(typeof globalThis !== "undefined" ? globalThis : this, function createPlayWordsCore() {
  const courseWords = [
    { word: "Cat", zh: "小猫", action: "jump", emoji: "🐱", letter: "C", sound: "c" },
    { word: "Dog", zh: "小狗", action: "wag", emoji: "🐶", letter: "D", sound: "d" },
    { word: "Bird", zh: "小鸟", action: "flap", emoji: "🐦", letter: "B", sound: "b" },
    { word: "Fish", zh: "小鱼", action: "swim", emoji: "🐠", letter: "F", sound: "f" },
    { word: "Apple", zh: "苹果", action: "jump", emoji: "🍎", letter: "A", sound: "a" },
    { word: "Banana", zh: "香蕉", action: "wag", emoji: "🍌", letter: "B", sound: "b" },
    { word: "Cake", zh: "蛋糕", action: "jump", emoji: "🍰", letter: "C", sound: "c" },
    { word: "Milk", zh: "牛奶", action: "swim", emoji: "🥛", letter: "M", sound: "m" },
    { word: "Run", zh: "跑", action: "swim", emoji: "🏃", letter: "R", sound: "r" },
    { word: "Jump", zh: "跳", action: "jump", emoji: "🦘", letter: "J", sound: "j" },
    { word: "Clap", zh: "拍手", action: "wag", emoji: "👏", letter: "C", sound: "c" },
    { word: "Sing", zh: "唱歌", action: "flap", emoji: "🎤", letter: "S", sound: "s" },
    { word: "Bed", zh: "床", action: "jump", emoji: "🛏️", letter: "B", sound: "b" },
    { word: "Cup", zh: "杯子", action: "wag", emoji: "☕", letter: "C", sound: "c" },
    { word: "Ball", zh: "球", action: "jump", emoji: "⚽", letter: "B", sound: "b" },
    { word: "Book", zh: "书", action: "flap", emoji: "📘", letter: "B", sound: "b" },
    { word: "Lion", zh: "狮子", action: "jump", emoji: "🦁", letter: "L", sound: "l" },
    { word: "Frog", zh: "青蛙", action: "jump", emoji: "🐸", letter: "F", sound: "f" },
    { word: "Bee", zh: "蜜蜂", action: "flap", emoji: "🐝", letter: "B", sound: "b" },
    { word: "Duck", zh: "鸭子", action: "wag", emoji: "🦆", letter: "D", sound: "d" },
    { word: "Egg", zh: "鸡蛋", action: "jump", emoji: "🥚", letter: "E", sound: "e" },
    { word: "Juice", zh: "果汁", action: "wag", emoji: "🧃", letter: "J", sound: "j" },
    { word: "Rice", zh: "米饭", action: "swim", emoji: "🍚", letter: "R", sound: "r" },
    { word: "Cookie", zh: "饼干", action: "jump", emoji: "🍪", letter: "C", sound: "c" },
    { word: "Dance", zh: "跳舞", action: "wag", emoji: "💃", letter: "D", sound: "d" },
    { word: "Sleep", zh: "睡觉", action: "swim", emoji: "😴", letter: "S", sound: "s" },
    { word: "Read", zh: "阅读", action: "jump", emoji: "📖", letter: "R", sound: "r" },
    { word: "Draw", zh: "画画", action: "wag", emoji: "🖍️", letter: "D", sound: "d" },
    { word: "Door", zh: "门", action: "swim", emoji: "🚪", letter: "D", sound: "d" },
    { word: "Chair", zh: "椅子", action: "wag", emoji: "🪑", letter: "C", sound: "c" },
    { word: "Lamp", zh: "台灯", action: "jump", emoji: "💡", letter: "L", sound: "l" },
    { word: "Toy", zh: "玩具", action: "wag", emoji: "🧸", letter: "T", sound: "t" },
    { word: "Red", zh: "红色", action: "jump", emoji: "🔴", letter: "R", sound: "r", phrase: "red apple", scene: "The apple is red.", rhyme: "Red, red, touch your head." },
    { word: "Blue", zh: "蓝色", action: "swim", emoji: "🔵", letter: "B", sound: "b", phrase: "blue sky", scene: "The sky is blue.", rhyme: "Blue, blue, I see you." },
    { word: "Yellow", zh: "黄色", action: "jump", emoji: "🟡", letter: "Y", sound: "y", phrase: "yellow sun", scene: "The sun is yellow.", rhyme: "Yellow, yellow, soft and mellow." },
    { word: "Green", zh: "绿色", action: "wag", emoji: "🟢", letter: "G", sound: "g", phrase: "green leaf", scene: "The leaf is green.", rhyme: "Green, green, nice and clean." },
    { word: "One", zh: "一", action: "jump", emoji: "1️⃣", letter: "O", sound: "o", phrase: "one ball", scene: "I have one ball.", rhyme: "One, one, learning is fun." },
    { word: "Two", zh: "二", action: "wag", emoji: "2️⃣", letter: "T", sound: "t", phrase: "two eyes", scene: "I have two eyes.", rhyme: "Two, two, me and you." },
    { word: "Three", zh: "三", action: "flap", emoji: "3️⃣", letter: "T", sound: "th", phrase: "three birds", scene: "I see three birds.", rhyme: "Three, three, count with me." },
    { word: "Four", zh: "四", action: "swim", emoji: "4️⃣", letter: "F", sound: "f", phrase: "four fish", scene: "I see four fish.", rhyme: "Four, four, open the door." },
    { word: "Mom", zh: "妈妈", action: "wag", emoji: "👩", letter: "M", sound: "m", phrase: "my mom", scene: "I love Mom.", rhyme: "Mom, mom, sing a song." },
    { word: "Dad", zh: "爸爸", action: "jump", emoji: "👨", letter: "D", sound: "d", phrase: "my dad", scene: "I love Dad.", rhyme: "Dad, dad, clap like that." },
    { word: "Baby", zh: "宝宝", action: "swim", emoji: "👶", letter: "B", sound: "b", phrase: "little baby", scene: "The baby smiles.", rhyme: "Baby, baby, wave to me." },
    { word: "Home", zh: "家", action: "jump", emoji: "🏠", letter: "H", sound: "h", phrase: "go home", scene: "I go home.", rhyme: "Home, home, warm as foam." },
    { word: "Head", zh: "头", action: "jump", emoji: "🙂", letter: "H", sound: "h", phrase: "my head", scene: "Touch your head.", rhyme: "Head, head, nod your head." },
    { word: "Eye", zh: "眼睛", action: "wag", emoji: "👁️", letter: "E", sound: "e", phrase: "one eye", scene: "I see with my eyes.", rhyme: "Eye, eye, look up high." },
    { word: "Nose", zh: "鼻子", action: "swim", emoji: "👃", letter: "N", sound: "n", phrase: "my nose", scene: "Touch your nose.", rhyme: "Nose, nose, smell a rose." },
    { word: "Hand", zh: "手", action: "wag", emoji: "✋", letter: "H", sound: "h", phrase: "my hand", scene: "Wave your hand.", rhyme: "Hand, hand, make a band." },
    { word: "Happy", zh: "开心", action: "jump", emoji: "😊", letter: "H", sound: "h", phrase: "feel happy", scene: "I am happy.", rhyme: "Happy, happy, tap, tap, tap." },
    { word: "Sad", zh: "难过", action: "swim", emoji: "😢", letter: "S", sound: "s", phrase: "feel sad", scene: "I feel sad.", rhyme: "Sad, sad, hug Mom and Dad." },
    { word: "Tired", zh: "累了", action: "swim", emoji: "🥱", letter: "T", sound: "t", phrase: "feel tired", scene: "I am tired.", rhyme: "Tired, tired, rest your head." },
    { word: "Funny", zh: "有趣", action: "jump", emoji: "😄", letter: "F", sound: "f", phrase: "so funny", scene: "This is funny.", rhyme: "Funny, funny, sunny day." },
    { word: "Hat", zh: "帽子", action: "jump", emoji: "🧢", letter: "H", sound: "h", phrase: "a blue hat", scene: "I wear a hat.", rhyme: "Hat, hat, pat your hat." },
    { word: "Shoes", zh: "鞋子", action: "wag", emoji: "👟", letter: "S", sound: "sh", phrase: "my shoes", scene: "I wear shoes.", rhyme: "Shoes, shoes, choose your shoes." },
    { word: "Coat", zh: "外套", action: "swim", emoji: "🧥", letter: "C", sound: "c", phrase: "a warm coat", scene: "I wear a coat.", rhyme: "Coat, coat, button your coat." },
    { word: "Socks", zh: "袜子", action: "wag", emoji: "🧦", letter: "S", sound: "s", phrase: "warm socks", scene: "These are my socks.", rhyme: "Socks, socks, tick tock." },
    { word: "Sun", zh: "太阳", action: "jump", emoji: "☀️", letter: "S", sound: "s", phrase: "bright sun", scene: "The sun is up.", rhyme: "Sun, sun, run in the sun." },
    { word: "Rain", zh: "雨", action: "swim", emoji: "🌧️", letter: "R", sound: "r", phrase: "soft rain", scene: "I hear the rain.", rhyme: "Rain, rain, tap the pane." },
    { word: "Wind", zh: "风", action: "flap", emoji: "💨", letter: "W", sound: "w", phrase: "strong wind", scene: "The wind blows.", rhyme: "Wind, wind, spin and grin." },
    { word: "Snow", zh: "雪", action: "swim", emoji: "❄️", letter: "S", sound: "s", phrase: "white snow", scene: "I see snow.", rhyme: "Snow, snow, soft and slow." },
    { word: "Circle", zh: "圆形", action: "swim", emoji: "⭕", letter: "C", sound: "c", phrase: "a big circle", scene: "This is a circle.", rhyme: "Circle, circle, round we go." },
    { word: "Star", zh: "星星", action: "jump", emoji: "⭐", letter: "S", sound: "s", phrase: "bright star", scene: "I see a star.", rhyme: "Star, star, shine afar." },
    { word: "Square", zh: "正方形", action: "wag", emoji: "◼️", letter: "S", sound: "s", phrase: "a small square", scene: "This is a square.", rhyme: "Square, square, draw it there." },
    { word: "Heart", zh: "爱心", action: "jump", emoji: "❤️", letter: "H", sound: "h", phrase: "red heart", scene: "I see a heart.", rhyme: "Heart, heart, love is art." },
    { word: "Pen", zh: "笔", action: "wag", emoji: "🖊️", letter: "P", sound: "p", phrase: "a blue pen", scene: "I use a pen.", rhyme: "Pen, pen, write again." },
    { word: "Bag", zh: "书包", action: "jump", emoji: "🎒", letter: "B", sound: "b", phrase: "my school bag", scene: "This is my bag.", rhyme: "Bag, bag, tag your bag." },
    { word: "Desk", zh: "课桌", action: "swim", emoji: "🧑‍🏫", letter: "D", sound: "d", phrase: "my desk", scene: "I sit at my desk.", rhyme: "Desk, desk, do your best." },
    { word: "Teacher", zh: "老师", action: "flap", emoji: "👩‍🏫", letter: "T", sound: "t", phrase: "my teacher", scene: "Hello, teacher.", rhyme: "Teacher, teacher, help me learn." },
    { word: "Tree", zh: "树", action: "flap", emoji: "🌳", letter: "T", sound: "t", phrase: "a tall tree", scene: "I see a tree.", rhyme: "Tree, tree, wave with me." },
    { word: "Flower", zh: "花", action: "wag", emoji: "🌸", letter: "F", sound: "f", phrase: "a pink flower", scene: "The flower is pretty.", rhyme: "Flower, flower, smell the flower." },
    { word: "Moon", zh: "月亮", action: "swim", emoji: "🌙", letter: "M", sound: "m", phrase: "the moon", scene: "The moon is bright.", rhyme: "Moon, moon, see you soon." },
    { word: "Sea", zh: "大海", action: "swim", emoji: "🌊", letter: "S", sound: "s", phrase: "blue sea", scene: "I see the sea.", rhyme: "Sea, sea, splash with me." },
    { word: "Car", zh: "汽车", action: "swim", emoji: "🚗", letter: "C", sound: "c", phrase: "a red car", scene: "The car can go.", rhyme: "Car, car, near and far." },
    { word: "Bus", zh: "公交车", action: "wag", emoji: "🚌", letter: "B", sound: "b", phrase: "a big bus", scene: "I ride a bus.", rhyme: "Bus, bus, ride with us." },
    { word: "Train", zh: "火车", action: "swim", emoji: "🚆", letter: "T", sound: "t", phrase: "a long train", scene: "The train is fast.", rhyme: "Train, train, down the lane." },
    { word: "Plane", zh: "飞机", action: "flap", emoji: "✈️", letter: "P", sound: "p", phrase: "a big plane", scene: "The plane can fly.", rhyme: "Plane, plane, fly again." },
    { word: "Hello", zh: "你好", action: "wag", emoji: "👋", letter: "H", sound: "h", phrase: "say hello", scene: "Hello, my friend.", rhyme: "Hello, hello, off we go." },
    { word: "Please", zh: "请", action: "jump", emoji: "🙏", letter: "P", sound: "p", phrase: "please help", scene: "Please help me.", rhyme: "Please, please, say it with ease." },
    { word: "Thanks", zh: "谢谢", action: "wag", emoji: "💛", letter: "T", sound: "th", phrase: "say thanks", scene: "Thanks, Mom.", rhyme: "Thanks, thanks, big happy thanks." },
    { word: "Bye", zh: "再见", action: "flap", emoji: "👋", letter: "B", sound: "b", phrase: "say bye", scene: "Bye, see you.", rhyme: "Bye, bye, wave to the sky." },
    { word: "Rabbit", zh: "兔子", action: "jump", emoji: "🐰", letter: "R", sound: "r", phrase: "a white rabbit", scene: "The rabbit can hop.", rhyme: "Rabbit, rabbit, hop so fast." },
    { word: "Bear", zh: "熊", action: "wag", emoji: "🐻", letter: "B", sound: "b", phrase: "a big bear", scene: "The bear is big.", rhyme: "Bear, bear, sit right there." },
    { word: "Tiger", zh: "老虎", action: "jump", emoji: "🐯", letter: "T", sound: "t", phrase: "a strong tiger", scene: "The tiger can run.", rhyme: "Tiger, tiger, orange and bright." },
    { word: "Monkey", zh: "猴子", action: "flap", emoji: "🐵", letter: "M", sound: "m", phrase: "a funny monkey", scene: "The monkey can climb.", rhyme: "Monkey, monkey, swing with me." },
    { word: "Cow", zh: "奶牛", action: "wag", emoji: "🐮", letter: "C", sound: "c", phrase: "a black cow", scene: "The cow says moo.", rhyme: "Cow, cow, moo out loud." },
    { word: "Pig", zh: "猪", action: "swim", emoji: "🐷", letter: "P", sound: "p", phrase: "a pink pig", scene: "The pig is pink.", rhyme: "Pig, pig, dance a jig." },
    { word: "Sheep", zh: "绵羊", action: "wag", emoji: "🐑", letter: "S", sound: "sh", phrase: "a soft sheep", scene: "The sheep is soft.", rhyme: "Sheep, sheep, go to sleep." },
    { word: "Horse", zh: "马", action: "jump", emoji: "🐴", letter: "H", sound: "h", phrase: "a fast horse", scene: "The horse can run.", rhyme: "Horse, horse, run your course." },
    { word: "Bread", zh: "面包", action: "jump", emoji: "🍞", letter: "B", sound: "b", phrase: "warm bread", scene: "I eat bread.", rhyme: "Bread, bread, breakfast bread." },
    { word: "Water", zh: "水", action: "swim", emoji: "💧", letter: "W", sound: "w", phrase: "cold water", scene: "I drink water.", rhyme: "Water, water, sip and smile." },
    { word: "Grape", zh: "葡萄", action: "wag", emoji: "🍇", letter: "G", sound: "g", phrase: "purple grapes", scene: "I like grapes.", rhyme: "Grape, grape, on my plate." },
    { word: "Pizza", zh: "披萨", action: "jump", emoji: "🍕", letter: "P", sound: "p", phrase: "hot pizza", scene: "The pizza is hot.", rhyme: "Pizza, pizza, yummy slice." },
    { word: "Noodles", zh: "面条", action: "swim", emoji: "🍜", letter: "N", sound: "n", phrase: "long noodles", scene: "I eat noodles.", rhyme: "Noodles, noodles, twist and twirl." },
    { word: "IceCream", zh: "冰淇淋", action: "jump", emoji: "🍦", letter: "I", sound: "i", phrase: "cold ice cream", scene: "I like ice cream.", rhyme: "Ice cream, ice cream, sweet dream." },
    { word: "Cheese", zh: "奶酪", action: "wag", emoji: "🧀", letter: "C", sound: "ch", phrase: "yellow cheese", scene: "The cheese is yellow.", rhyme: "Cheese, cheese, smile please." },
    { word: "Soup", zh: "汤", action: "swim", emoji: "🥣", letter: "S", sound: "s", phrase: "warm soup", scene: "I drink soup.", rhyme: "Soup, soup, scoop the soup." },
    { word: "Walk", zh: "走路", action: "wag", emoji: "🚶", letter: "W", sound: "w", phrase: "walk slowly", scene: "I can walk.", rhyme: "Walk, walk, tick tock." },
    { word: "Swim", zh: "游泳", action: "swim", emoji: "🏊", letter: "S", sound: "s", phrase: "swim fast", scene: "I can swim.", rhyme: "Swim, swim, splash and grin." },
    { word: "Eat", zh: "吃", action: "jump", emoji: "🍽️", letter: "E", sound: "e", phrase: "eat lunch", scene: "I eat rice.", rhyme: "Eat, eat, take a seat." },
    { word: "Drink", zh: "喝", action: "swim", emoji: "🥤", letter: "D", sound: "d", phrase: "drink water", scene: "I drink milk.", rhyme: "Drink, drink, sip and think." },
    { word: "Look", zh: "看", action: "jump", emoji: "👀", letter: "L", sound: "l", phrase: "look here", scene: "Look at me.", rhyme: "Look, look, open the book." },
    { word: "Listen", zh: "听", action: "wag", emoji: "👂", letter: "L", sound: "l", phrase: "listen carefully", scene: "Listen to the word.", rhyme: "Listen, listen, sparkle and glisten." },
    { word: "Smile", zh: "微笑", action: "jump", emoji: "🙂", letter: "S", sound: "s", phrase: "big smile", scene: "I can smile.", rhyme: "Smile, smile, stay a while." },
    { word: "Wash", zh: "洗", action: "swim", emoji: "🧼", letter: "W", sound: "w", phrase: "wash hands", scene: "I wash my hands.", rhyme: "Wash, wash, splash, splash." },
    { word: "Table", zh: "桌子", action: "wag", emoji: "🪵", letter: "T", sound: "t", phrase: "a small table", scene: "The cup is on the table.", rhyme: "Table, table, strong and stable." },
    { word: "Window", zh: "窗户", action: "flap", emoji: "🪟", letter: "W", sound: "w", phrase: "open window", scene: "Open the window.", rhyme: "Window, window, let wind in." },
    { word: "Sofa", zh: "沙发", action: "swim", emoji: "🛋️", letter: "S", sound: "s", phrase: "soft sofa", scene: "I sit on the sofa.", rhyme: "Sofa, sofa, sit with me." },
    { word: "Pillow", zh: "枕头", action: "swim", emoji: "🛌", letter: "P", sound: "p", phrase: "soft pillow", scene: "My pillow is soft.", rhyme: "Pillow, pillow, sleepy head." },
    { word: "Clock", zh: "钟表", action: "wag", emoji: "🕒", letter: "C", sound: "c", phrase: "a round clock", scene: "The clock ticks.", rhyme: "Clock, clock, tick tock." },
    { word: "TV", zh: "电视", action: "jump", emoji: "📺", letter: "T", sound: "t", phrase: "watch TV", scene: "I watch TV.", rhyme: "TV, TV, look and see." },
    { word: "Phone", zh: "电话", action: "wag", emoji: "☎️", letter: "P", sound: "f", phrase: "my phone", scene: "The phone rings.", rhyme: "Phone, phone, ring at home." },
    { word: "Brush", zh: "牙刷", action: "wag", emoji: "🪥", letter: "B", sound: "br", phrase: "my brush", scene: "I brush my teeth.", rhyme: "Brush, brush, rush, rush." },
    { word: "Black", zh: "黑色", action: "swim", emoji: "⚫", letter: "B", sound: "b", phrase: "black cat", scene: "The cat is black.", rhyme: "Black, black, tap your back." },
    { word: "White", zh: "白色", action: "jump", emoji: "⚪", letter: "W", sound: "w", phrase: "white snow", scene: "The snow is white.", rhyme: "White, white, soft and bright." },
    { word: "Pink", zh: "粉色", action: "wag", emoji: "🌸", letter: "P", sound: "p", phrase: "pink flower", scene: "The flower is pink.", rhyme: "Pink, pink, blink, blink." },
    { word: "Purple", zh: "紫色", action: "jump", emoji: "🟣", letter: "P", sound: "p", phrase: "purple grape", scene: "The grape is purple.", rhyme: "Purple, purple, circle, circle." },
    { word: "Orange", zh: "橙色", action: "jump", emoji: "🟠", letter: "O", sound: "o", phrase: "orange ball", scene: "The ball is orange.", rhyme: "Orange, orange, bright and warm." },
    { word: "Brown", zh: "棕色", action: "wag", emoji: "🟤", letter: "B", sound: "b", phrase: "brown bear", scene: "The bear is brown.", rhyme: "Brown, brown, turn around." },
    { word: "Gray", zh: "灰色", action: "swim", emoji: "🩶", letter: "G", sound: "g", phrase: "gray cloud", scene: "The cloud is gray.", rhyme: "Gray, gray, cloudy day." },
    { word: "Gold", zh: "金色", action: "jump", emoji: "🌟", letter: "G", sound: "g", phrase: "gold star", scene: "The star is gold.", rhyme: "Gold, gold, bright and bold." },
    { word: "Five", zh: "五", action: "jump", emoji: "5️⃣", letter: "F", sound: "f", phrase: "five stars", scene: "I see five stars.", rhyme: "Five, five, jump and jive." },
    { word: "Six", zh: "六", action: "wag", emoji: "6️⃣", letter: "S", sound: "s", phrase: "six socks", scene: "I count six socks.", rhyme: "Six, six, tap the sticks." },
    { word: "Seven", zh: "七", action: "flap", emoji: "7️⃣", letter: "S", sound: "s", phrase: "seven days", scene: "Seven days in a week.", rhyme: "Seven, seven, look at heaven." },
    { word: "Eight", zh: "八", action: "swim", emoji: "8️⃣", letter: "E", sound: "e", phrase: "eight eggs", scene: "I see eight eggs.", rhyme: "Eight, eight, close the gate." },
    { word: "Nine", zh: "九", action: "jump", emoji: "9️⃣", letter: "N", sound: "n", phrase: "nine toys", scene: "I have nine toys.", rhyme: "Nine, nine, draw a line." },
    { word: "Ten", zh: "十", action: "wag", emoji: "🔟", letter: "T", sound: "t", phrase: "ten fingers", scene: "I have ten fingers.", rhyme: "Ten, ten, count again." },
    { word: "Zero", zh: "零", action: "swim", emoji: "0️⃣", letter: "Z", sound: "z", phrase: "zero cookies", scene: "I have zero cookies.", rhyme: "Zero, zero, start from zero." },
    { word: "Count", zh: "数数", action: "jump", emoji: "🔢", letter: "C", sound: "c", phrase: "count numbers", scene: "I can count.", rhyme: "Count, count, up the mount." },
    { word: "Grandma", zh: "奶奶", action: "wag", emoji: "👵", letter: "G", sound: "g", phrase: "my grandma", scene: "I love Grandma.", rhyme: "Grandma, Grandma, hug me tight." },
    { word: "Grandpa", zh: "爷爷", action: "jump", emoji: "👴", letter: "G", sound: "g", phrase: "my grandpa", scene: "I love Grandpa.", rhyme: "Grandpa, Grandpa, smile so bright." },
    { word: "Sister", zh: "姐妹", action: "flap", emoji: "👧", letter: "S", sound: "s", phrase: "my sister", scene: "My sister can sing.", rhyme: "Sister, sister, dance with me." },
    { word: "Brother", zh: "兄弟", action: "jump", emoji: "👦", letter: "B", sound: "br", phrase: "my brother", scene: "My brother can run.", rhyme: "Brother, brother, help each other." },
    { word: "Friend", zh: "朋友", action: "wag", emoji: "🧒", letter: "F", sound: "f", phrase: "my friend", scene: "Hello, my friend.", rhyme: "Friend, friend, play again." },
    { word: "Boy", zh: "男孩", action: "jump", emoji: "👦", letter: "B", sound: "b", phrase: "a little boy", scene: "The boy can jump.", rhyme: "Boy, boy, share your toy." },
    { word: "Girl", zh: "女孩", action: "flap", emoji: "👧", letter: "G", sound: "g", phrase: "a little girl", scene: "The girl can read.", rhyme: "Girl, girl, twirl, twirl." },
    { word: "Family", zh: "家庭", action: "wag", emoji: "👨‍👩‍👧", letter: "F", sound: "f", phrase: "my family", scene: "I love my family.", rhyme: "Family, family, you and me." },
    { word: "Mouth", zh: "嘴巴", action: "wag", emoji: "👄", letter: "M", sound: "m", phrase: "my mouth", scene: "I speak with my mouth.", rhyme: "Mouth, mouth, north and south." },
    { word: "Ear", zh: "耳朵", action: "flap", emoji: "👂", letter: "E", sound: "e", phrase: "my ear", scene: "I listen with my ears.", rhyme: "Ear, ear, I can hear." },
    { word: "Foot", zh: "脚", action: "jump", emoji: "🦶", letter: "F", sound: "f", phrase: "my foot", scene: "Touch your foot.", rhyme: "Foot, foot, step and put." },
    { word: "Leg", zh: "腿", action: "swim", emoji: "🦵", letter: "L", sound: "l", phrase: "my leg", scene: "I kick with my leg.", rhyme: "Leg, leg, hop like an egg." },
    { word: "Arm", zh: "胳膊", action: "wag", emoji: "💪", letter: "A", sound: "a", phrase: "my arm", scene: "Wave your arm.", rhyme: "Arm, arm, strong and warm." },
    { word: "Hair", zh: "头发", action: "swim", emoji: "💇", letter: "H", sound: "h", phrase: "my hair", scene: "My hair is soft.", rhyme: "Hair, hair, brush with care." },
    { word: "Face", zh: "脸", action: "jump", emoji: "😀", letter: "F", sound: "f", phrase: "my face", scene: "Wash your face.", rhyme: "Face, face, happy place." },
    { word: "Tooth", zh: "牙齿", action: "wag", emoji: "🦷", letter: "T", sound: "t", phrase: "one tooth", scene: "Brush your teeth.", rhyme: "Tooth, tooth, tell the truth." },
    { word: "Angry", zh: "生气", action: "jump", emoji: "😠", letter: "A", sound: "a", phrase: "feel angry", scene: "I feel angry.", rhyme: "Angry, angry, breathe with me." },
    { word: "Scared", zh: "害怕", action: "swim", emoji: "😨", letter: "S", sound: "s", phrase: "feel scared", scene: "I feel scared.", rhyme: "Scared, scared, hold my hand." },
    { word: "Excited", zh: "兴奋", action: "jump", emoji: "🤩", letter: "E", sound: "e", phrase: "feel excited", scene: "I am excited.", rhyme: "Excited, excited, clap and play." },
    { word: "Calm", zh: "平静", action: "swim", emoji: "😌", letter: "C", sound: "c", phrase: "feel calm", scene: "I feel calm.", rhyme: "Calm, calm, soft as a song." },
    { word: "Sleepy", zh: "困了", action: "swim", emoji: "😪", letter: "S", sound: "s", phrase: "feel sleepy", scene: "I am sleepy.", rhyme: "Sleepy, sleepy, close your eyes." },
    { word: "Proud", zh: "自豪", action: "jump", emoji: "🥳", letter: "P", sound: "p", phrase: "feel proud", scene: "I feel proud.", rhyme: "Proud, proud, say it loud." },
    { word: "Shy", zh: "害羞", action: "wag", emoji: "☺️", letter: "S", sound: "sh", phrase: "feel shy", scene: "I feel shy.", rhyme: "Shy, shy, wave goodbye." },
    { word: "Okay", zh: "还好", action: "wag", emoji: "👌", letter: "O", sound: "o", phrase: "feel okay", scene: "I am okay.", rhyme: "Okay, okay, start the day." },
    { word: "Shirt", zh: "衬衫", action: "wag", emoji: "👕", letter: "S", sound: "sh", phrase: "a blue shirt", scene: "I wear a shirt.", rhyme: "Shirt, shirt, swish your shirt." },
    { word: "Pants", zh: "裤子", action: "jump", emoji: "👖", letter: "P", sound: "p", phrase: "long pants", scene: "I wear pants.", rhyme: "Pants, pants, dance, dance." },
    { word: "Dress", zh: "连衣裙", action: "flap", emoji: "👗", letter: "D", sound: "d", phrase: "a pretty dress", scene: "I wear a dress.", rhyme: "Dress, dress, twirl and bless." },
    { word: "Skirt", zh: "裙子", action: "wag", emoji: "👚", letter: "S", sound: "sk", phrase: "a pink skirt", scene: "This is my skirt.", rhyme: "Skirt, skirt, spin your skirt." },
    { word: "Shorts", zh: "短裤", action: "jump", emoji: "🩳", letter: "S", sound: "sh", phrase: "blue shorts", scene: "I wear shorts.", rhyme: "Shorts, shorts, sports, sports." },
    { word: "Scarf", zh: "围巾", action: "flap", emoji: "🧣", letter: "S", sound: "sk", phrase: "warm scarf", scene: "I wear a scarf.", rhyme: "Scarf, scarf, warm my neck." },
    { word: "Gloves", zh: "手套", action: "wag", emoji: "🧤", letter: "G", sound: "g", phrase: "red gloves", scene: "I wear gloves.", rhyme: "Gloves, gloves, warm with love." },
    { word: "Boots", zh: "靴子", action: "jump", emoji: "🥾", letter: "B", sound: "b", phrase: "brown boots", scene: "I wear boots.", rhyme: "Boots, boots, step in boots." },
    { word: "Cloud", zh: "云", action: "flap", emoji: "☁️", letter: "C", sound: "c", phrase: "white cloud", scene: "I see a cloud.", rhyme: "Cloud, cloud, soft and proud." },
    { word: "Storm", zh: "暴风雨", action: "swim", emoji: "⛈️", letter: "S", sound: "st", phrase: "big storm", scene: "The storm is loud.", rhyme: "Storm, storm, stay warm." },
    { word: "Hot", zh: "热", action: "jump", emoji: "🥵", letter: "H", sound: "h", phrase: "hot day", scene: "It is hot.", rhyme: "Hot, hot, drink a lot." },
    { word: "Cold", zh: "冷", action: "swim", emoji: "🥶", letter: "C", sound: "c", phrase: "cold day", scene: "It is cold.", rhyme: "Cold, cold, hold, hold." },
    { word: "Warm", zh: "温暖", action: "wag", emoji: "🌤️", letter: "W", sound: "w", phrase: "warm sun", scene: "It is warm.", rhyme: "Warm, warm, soft and warm." },
    { word: "Cool", zh: "凉爽", action: "swim", emoji: "🍃", letter: "C", sound: "c", phrase: "cool wind", scene: "It is cool.", rhyme: "Cool, cool, back to school." },
    { word: "Sunny", zh: "晴朗", action: "jump", emoji: "🌞", letter: "S", sound: "s", phrase: "sunny day", scene: "It is sunny.", rhyme: "Sunny, sunny, bright and funny." },
    { word: "Foggy", zh: "有雾", action: "swim", emoji: "🌫️", letter: "F", sound: "f", phrase: "foggy morning", scene: "It is foggy.", rhyme: "Foggy, foggy, walk slowly." },
    { word: "Triangle", zh: "三角形", action: "jump", emoji: "🔺", letter: "T", sound: "t", phrase: "red triangle", scene: "This is a triangle.", rhyme: "Triangle, triangle, three sides tall." },
    { word: "Rectangle", zh: "长方形", action: "wag", emoji: "▭", letter: "R", sound: "r", phrase: "long rectangle", scene: "This is a rectangle.", rhyme: "Rectangle, rectangle, long and strong." },
    { word: "Diamond", zh: "菱形", action: "swim", emoji: "🔷", letter: "D", sound: "d", phrase: "blue diamond", scene: "This is a diamond.", rhyme: "Diamond, diamond, shine and glow." },
    { word: "Oval", zh: "椭圆形", action: "wag", emoji: "🥚", letter: "O", sound: "o", phrase: "small oval", scene: "This is an oval.", rhyme: "Oval, oval, roll so slow." },
    { word: "Pencil", zh: "铅笔", action: "wag", emoji: "✏️", letter: "P", sound: "p", phrase: "yellow pencil", scene: "I use a pencil.", rhyme: "Pencil, pencil, write your name." },
    { word: "Ruler", zh: "尺子", action: "jump", emoji: "📏", letter: "R", sound: "r", phrase: "long ruler", scene: "I use a ruler.", rhyme: "Ruler, ruler, straight and neat." },
    { word: "Eraser", zh: "橡皮", action: "swim", emoji: "🧽", letter: "E", sound: "e", phrase: "pink eraser", scene: "I use an eraser.", rhyme: "Eraser, eraser, rub away." },
    { word: "Crayon", zh: "蜡笔", action: "wag", emoji: "🖍️", letter: "C", sound: "c", phrase: "red crayon", scene: "I use a crayon.", rhyme: "Crayon, crayon, color and play." },
    { word: "Paper", zh: "纸", action: "flap", emoji: "📄", letter: "P", sound: "p", phrase: "white paper", scene: "I draw on paper.", rhyme: "Paper, paper, fold and play." },
    { word: "Glue", zh: "胶水", action: "swim", emoji: "🧴", letter: "G", sound: "g", phrase: "sticky glue", scene: "I use glue.", rhyme: "Glue, glue, stick it true." },
    { word: "Scissors", zh: "剪刀", action: "wag", emoji: "✂️", letter: "S", sound: "s", phrase: "safe scissors", scene: "I use scissors.", rhyme: "Scissors, scissors, snip, snip." },
    { word: "Classroom", zh: "教室", action: "jump", emoji: "🏫", letter: "C", sound: "c", phrase: "my classroom", scene: "I learn in the classroom.", rhyme: "Classroom, classroom, learn and bloom." },
    { word: "Mountain", zh: "山", action: "jump", emoji: "⛰️", letter: "M", sound: "m", phrase: "big mountain", scene: "I see a mountain.", rhyme: "Mountain, mountain, high and tall." },
    { word: "River", zh: "河流", action: "swim", emoji: "🏞️", letter: "R", sound: "r", phrase: "long river", scene: "The river is long.", rhyme: "River, river, shimmer, shimmer." },
    { word: "Leaf", zh: "叶子", action: "flap", emoji: "🍃", letter: "L", sound: "l", phrase: "green leaf", scene: "The leaf is green.", rhyme: "Leaf, leaf, fly so brief." },
    { word: "Rock", zh: "石头", action: "wag", emoji: "🪨", letter: "R", sound: "r", phrase: "small rock", scene: "I see a rock.", rhyme: "Rock, rock, knock, knock." },
    { word: "Grass", zh: "草地", action: "swim", emoji: "🌱", letter: "G", sound: "g", phrase: "green grass", scene: "I sit on the grass.", rhyme: "Grass, grass, soft to pass." },
    { word: "Sky", zh: "天空", action: "flap", emoji: "🌌", letter: "S", sound: "s", phrase: "blue sky", scene: "The sky is blue.", rhyme: "Sky, sky, way up high." },
    { word: "Lake", zh: "湖", action: "swim", emoji: "🏝️", letter: "L", sound: "l", phrase: "quiet lake", scene: "I see a lake.", rhyme: "Lake, lake, wake, wake." },
    { word: "Hill", zh: "小山", action: "jump", emoji: "🌄", letter: "H", sound: "h", phrase: "small hill", scene: "I walk up the hill.", rhyme: "Hill, hill, climb with will." },
    { word: "Bike", zh: "自行车", action: "swim", emoji: "🚲", letter: "B", sound: "b", phrase: "ride a bike", scene: "I ride a bike.", rhyme: "Bike, bike, ride and like." },
    { word: "Boat", zh: "船", action: "swim", emoji: "⛵", letter: "B", sound: "b", phrase: "small boat", scene: "The boat can float.", rhyme: "Boat, boat, float, float." },
    { word: "Taxi", zh: "出租车", action: "wag", emoji: "🚕", letter: "T", sound: "t", phrase: "yellow taxi", scene: "I see a taxi.", rhyme: "Taxi, taxi, take me home." },
    { word: "Ship", zh: "轮船", action: "swim", emoji: "🚢", letter: "S", sound: "sh", phrase: "big ship", scene: "The ship is big.", rhyme: "Ship, ship, on a trip." },
    { word: "Truck", zh: "卡车", action: "swim", emoji: "🚚", letter: "T", sound: "tr", phrase: "big truck", scene: "The truck is loud.", rhyme: "Truck, truck, good luck." },
    { word: "Scooter", zh: "滑板车", action: "wag", emoji: "🛴", letter: "S", sound: "s", phrase: "red scooter", scene: "I ride a scooter.", rhyme: "Scooter, scooter, zoom away." },
    { word: "Subway", zh: "地铁", action: "swim", emoji: "🚇", letter: "S", sound: "s", phrase: "fast subway", scene: "I take the subway.", rhyme: "Subway, subway, go today." },
    { word: "Rocket", zh: "火箭", action: "flap", emoji: "🚀", letter: "R", sound: "r", phrase: "fast rocket", scene: "The rocket goes up.", rhyme: "Rocket, rocket, to the sky." },
    { word: "Sorry", zh: "对不起", action: "wag", emoji: "🙏", letter: "S", sound: "s", phrase: "say sorry", scene: "Sorry, my friend.", rhyme: "Sorry, sorry, kind and sweet." },
    { word: "Welcome", zh: "欢迎", action: "jump", emoji: "🤗", letter: "W", sound: "w", phrase: "you are welcome", scene: "Welcome to class.", rhyme: "Welcome, welcome, come and play." },
    { word: "Morning", zh: "早上", action: "jump", emoji: "🌅", letter: "M", sound: "m", phrase: "good morning", scene: "Good morning, teacher.", rhyme: "Morning, morning, start the day." },
    { word: "Night", zh: "夜晚", action: "swim", emoji: "🌙", letter: "N", sound: "n", phrase: "good night", scene: "Good night, Mom.", rhyme: "Night, night, sleep tight." },
    { word: "Yes", zh: "是的", action: "jump", emoji: "✅", letter: "Y", sound: "y", phrase: "say yes", scene: "Yes, I can.", rhyme: "Yes, yes, do your best." },
    { word: "No", zh: "不", action: "wag", emoji: "❌", letter: "N", sound: "n", phrase: "say no", scene: "No, thank you.", rhyme: "No, no, slow, slow." },
    { word: "Good", zh: "好的", action: "jump", emoji: "👍", letter: "G", sound: "g", phrase: "good job", scene: "Good job!", rhyme: "Good, good, knock on wood." },
    { word: "Great", zh: "很棒", action: "jump", emoji: "🌈", letter: "G", sound: "gr", phrase: "great work", scene: "Great work!", rhyme: "Great, great, celebrate." },
  ];
  
  const wordExpressions = {
    Cat: { phrase: "a little cat", scene: "I see a cat.", rhyme: "Cat, cat, clap like that." },
    Dog: { phrase: "a happy dog", scene: "The dog can run.", rhyme: "Dog, dog, say hello." },
    Bird: { phrase: "a blue bird", scene: "The bird can fly.", rhyme: "Bird, bird, fly high." },
    Fish: { phrase: "a small fish", scene: "The fish can swim.", rhyme: "Fish, fish, swish, swish." },
    Apple: { phrase: "a red apple", scene: "I like apples.", rhyme: "Apple, apple, yum, yum." },
    Banana: { phrase: "a yellow banana", scene: "I eat a banana.", rhyme: "Banana, banana, peel and eat." },
    Cake: { phrase: "a sweet cake", scene: "This cake is yummy.", rhyme: "Cake, cake, take a bite." },
    Milk: { phrase: "a cup of milk", scene: "I drink milk.", rhyme: "Milk, milk, nice and white." },
    Run: { phrase: "run fast", scene: "I can run.", rhyme: "Run, run, under the sun." },
    Jump: { phrase: "jump high", scene: "I can jump.", rhyme: "Jump, jump, up and down." },
    Clap: { phrase: "clap hands", scene: "I clap my hands.", rhyme: "Clap, clap, make a sound." },
    Sing: { phrase: "sing a song", scene: "I can sing.", rhyme: "Sing, sing, ding, ding." },
    Bed: { phrase: "my little bed", scene: "I sleep in bed.", rhyme: "Bed, bed, sleepy head." },
    Cup: { phrase: "a blue cup", scene: "This is my cup.", rhyme: "Cup, cup, drink it up." },
    Ball: { phrase: "a round ball", scene: "I kick the ball.", rhyme: "Ball, ball, bounce and fall." },
    Book: { phrase: "a story book", scene: "I read a book.", rhyme: "Book, book, take a look." },
    Lion: { phrase: "a big lion", scene: "The lion is strong.", rhyme: "Lion, lion, roar with me." },
    Frog: { phrase: "a green frog", scene: "The frog can jump.", rhyme: "Frog, frog, hop on a log." },
    Bee: { phrase: "a busy bee", scene: "The bee can buzz.", rhyme: "Bee, bee, buzz with me." },
    Duck: { phrase: "a yellow duck", scene: "The duck can swim.", rhyme: "Duck, duck, quack, quack." },
    Egg: { phrase: "a white egg", scene: "I see an egg.", rhyme: "Egg, egg, tap the peg." },
    Juice: { phrase: "apple juice", scene: "I drink juice.", rhyme: "Juice, juice, sweet and cool." },
    Rice: { phrase: "hot rice", scene: "I eat rice.", rhyme: "Rice, rice, very nice." },
    Cookie: { phrase: "a round cookie", scene: "I want a cookie.", rhyme: "Cookie, cookie, crunchy bite." },
    Dance: { phrase: "dance around", scene: "I can dance.", rhyme: "Dance, dance, move your feet." },
    Sleep: { phrase: "sleep well", scene: "I go to sleep.", rhyme: "Sleep, sleep, count the sheep." },
    Read: { phrase: "read a book", scene: "I read with Mom.", rhyme: "Read, read, learn and grow." },
    Draw: { phrase: "draw a picture", scene: "I draw a sun.", rhyme: "Draw, draw, color more." },
    Door: { phrase: "open the door", scene: "Please open the door.", rhyme: "Door, door, one step more." },
    Chair: { phrase: "sit on a chair", scene: "I sit on a chair.", rhyme: "Chair, chair, sit right there." },
    Lamp: { phrase: "turn on the lamp", scene: "The lamp is bright.", rhyme: "Lamp, lamp, light the room." },
    Toy: { phrase: "my favorite toy", scene: "I play with a toy.", rhyme: "Toy, toy, share your joy." },
  };
  
  const lessonTitles = [
    "Animal Friends 1",
    "Yummy Food 1",
    "Move My Body 1",
    "Around Home 1",
    "Animal Friends 2",
    "Yummy Food 2",
    "Move My Body 2",
    "Around Home 2",
    "Rainbow Colors 1",
    "First Numbers 1",
    "My Family 1",
    "My Body 1",
    "My Feelings 1",
    "My Clothes 1",
    "Weather Day 1",
    "Shapes I See 1",
    "School Time 1",
    "Nature Walk 1",
    "Things That Go 1",
    "Polite Words 1",
    "Animal Friends 3",
    "Animal Friends 4",
    "Yummy Food 3",
    "Yummy Food 4",
    "Move My Body 3",
    "Move My Body 4",
    "Around Home 3",
    "Around Home 4",
    "Rainbow Colors 2",
    "Rainbow Colors 3",
    "First Numbers 2",
    "First Numbers 3",
    "My Family 2",
    "My Family 3",
    "My Body 2",
    "My Body 3",
    "My Feelings 2",
    "My Feelings 3",
    "My Clothes 2",
    "My Clothes 3",
    "Weather Day 2",
    "Weather Day 3",
    "Shapes I See 2",
    "School Time 2",
    "School Time 3",
    "Nature Walk 2",
    "Nature Walk 3",
    "Things That Go 2",
    "Things That Go 3",
    "Polite Words 2",
    "Polite Words 3",
  ];
  
  const lessonSections = [
    "Animals",
    "Food",
    "Actions",
    "Home",
    "Animals",
    "Food",
    "Actions",
    "Home",
    "Colors",
    "Numbers",
    "Family",
    "Body",
    "Feelings",
    "Clothes",
    "Weather",
    "Shapes",
    "School",
    "Nature",
    "Transport",
    "Polite",
    "Animals",
    "Animals",
    "Food",
    "Food",
    "Actions",
    "Actions",
    "Home",
    "Home",
    "Colors",
    "Colors",
    "Numbers",
    "Numbers",
    "Family",
    "Family",
    "Body",
    "Body",
    "Feelings",
    "Feelings",
    "Clothes",
    "Clothes",
    "Weather",
    "Weather",
    "Shapes",
    "School",
    "School",
    "Nature",
    "Nature",
    "Transport",
    "Transport",
    "Polite",
    "Polite",
  ];
  
  const sectionStories = {
    Animals: {
      world: "Forest Island",
      title: "森林里谁在叫？",
      mission: "Buddy 听到一个声音，帮它找到森林朋友。",
      win: "You saved the forest friend!",
    },
    Food: {
      world: "Food Town",
      title: "野餐篮少了什么？",
      mission: "听一听、说一说，把食物放回野餐篮。",
      win: "Picnic sticker unlocked!",
    },
    Actions: {
      world: "Move Park",
      title: "动作小队出发！",
      mission: "跟着 Buddy 做动作，再大声说出来。",
      win: "Action badge unlocked!",
    },
    Home: {
      world: "Cozy Home",
      title: "家里藏着什么？",
      mission: "找到房间里的小物品，学会说它们。",
      win: "Home sticker unlocked!",
    },
    Weather: {
      world: "Weather Sky",
      title: "今天是什么天气？",
      mission: "看天空、听声音，帮 Buddy 选择天气。",
      win: "Weather badge unlocked!",
    },
    School: {
      world: "School Bus",
      title: "上学准备好了吗？",
      mission: "找到课堂用品，完成开学小任务。",
      win: "School sticker unlocked!",
    },
  };
  
  function lessonStoryFor(section) {
    return (
      sectionStories[section] || {
        world: `${section} World`,
        title: "Buddy 的英语小任务",
        mission: "听、看、说，完成今天的英语冒险。",
        win: "Sticker unlocked!",
      }
    );
  }
  
  const lessons = Array.from({ length: Math.ceil(courseWords.length / 4) }, (_, index) => {
    const section = lessonSections[index] || "Core";
    return {
      title: lessonTitles[index] || `Lesson ${index + 1}`,
      section,
      story: lessonStoryFor(section),
      words: courseWords.slice(index * 4, index * 4 + 4),
    };
  });

  return {
    courseWords,
    wordExpressions,
    lessonTitles,
    lessonSections,
    sectionStories,
    lessonStoryFor,
    lessons,
  };
});
